# Variances and Beliefs

Here I want to see whether pessimistic beliefs have an impact on the variance of the assets or not. 
<br\>
* First, I will write a function that returns a belief decompostition of a transition matrix, a real transition matrix and a corresponding belief matrix with pessimistic beliefs.
<br\>
* Then, I will write a class and corresponding functions, which distinguish between the two different kinds of transition matrices.
<br\>
* After that, I will simulate the asset choices given a interest rate, compute the variance of the assets series and compare them.
<br\>
* Finally, I will write a function which return a mean preserving spread of the state values given the belief matrix, then use that to compute another asset series which I can compare to the both before.



In [62]:
# First, I will write a function that returns a belief 
# decompostition of a transition matrix, a real transition 
# matrix and a corresponding belief matrix with pessimistic beliefs.

import numpy as np
from quantecon import MarkovChain

def trans_mat(P1, P3, epsilon):
    """
    Returns a transition matrix (for a markov chain) of the following form:
        
        Π = ((P1, P2, 0), (P2 - epsilon, P1, epsilon), (P4, P4, P3))
    
    where P2 = 1-P1 and P4 = 0.5*(1-P3)
    
    epsilon is the probability for the transition from the 2. to the 
    3. state.
    P1 is the probability to stay in the current state if the 
    current state is the 1. or 2. state.
    P3 ist the probability to stay in the 3rd state.
    2*P4 ist the probability to get out of the 3rd state.
    """
    P2, P4 = (1-P1), 0.5*(1-P3)
    
    Π = ((P1, P2, 0), (P2 - epsilon, P1, epsilon), (P4, P4, P3))
    
    return np.asarray(Π)


def belief_decompose(Π, z_vals):
    
    """
    Belief decomposition for a 3x3 matrix with the follwowing form:
        
        Π = ((P1, P2, 0), (P2 - epsilon, P1, epsilon), (P4, P4, P3))
        
    The belief matrix has the following form:
        
        Π_belief = (( P1, 0.5*P2, 0.5*P2, 0), 
                    (0.5*(P2-epsilon), P1, 0.5*(P2-epsilon), epsilon), 
                    ( 0, 0, P1, 1 - P1), 
                    (P4, P4, 0, P3))
    """
    
    P1, P2, P3, P4 = Π[0][0], Π[0][1], Π[2][2], Π[2][0]
    epsilon = Π[1][2]
    
    Π_belief = (( P1, 0.5*P2, 0.5*P2, 0), 
                (0.5*(P2-epsilon), P1, 0.5*(P2-epsilon), epsilon), 
                ( 0, 0, P1, 1 - P1), 
                (P4, P4, 0, P3))
        
    # rewrite the real transition matrix
    Π_real = ((P1, 0.5*P2, 0.5*P2, 0),
              (P2-epsilon, 0.5*P1, 0.5*P1, epsilon), 
              (P2-epsilon, 0.5*P1, 0.5*P1, epsilon), 
              (P4, 0.5*P4, 0.5*P4, P3))
    
    # adjust state space
    z_vals = np.asarray(z_vals)
    z_vals = np.insert(z_vals, 1, z_vals[1])
    
    return np.asarray(Π_real), np.asarray(Π_belief), np.asarray(z_vals)

# write code with which you can compute a mean-preserving-spread
# for the 'perceived' state space

def exp_val(z_vals, P_z):
    """
    This function gives you the weighted average of all states of a 
    markov chain in the long run.
    
    Parameters
    -----------
    
    z_vals : state values of the markov chain
    P_z : transition matrix
    """
    mc = MarkovChain(P_z, state_values = z_vals) # get the stationary probs
    return np.sum(mc.stationary_distributions * z_vals) # compute weighted average

def mean_preserving_states(z_vals, Π_real, Π_belief, err_tol):
    exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
    exp_belief = exp_val(z_vals=z_vals, P_z=Π_belief)
    z_vals_new = np.array(z_vals)
    diff = exp_real - exp_belief
    n = len(z_vals)
    
    s_dist = MarkovChain(Π_belief).stationary_distributions[0]
    w_high = s_dist[0]/(s_dist[0]+s_dist[-1]) #weight for high value state
    w_neg = 1 - w_high # weight for negatiive value state
    
    while abs(diff) > err_tol:
        if z_vals_new[-1] >= -0.3:
            z_vals_new[-1] = -0.3
            z_vals_new[0] = z_vals_new[0]+(w_high*diff)
            exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
            exp_belief = exp_val(z_vals=z_vals_new, P_z=Π_belief)
            diff = exp_real - exp_belief
        else:
            z_vals_new[0], z_vals_new[-1] = z_vals_new[0]+(w_high*diff), z_vals_new[-1]+(w_neg*diff)
            exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
            exp_belief = exp_val(z_vals=z_vals_new, P_z=Π_belief)
            diff = exp_real - exp_belief
            #print('{}, {}'.format(exp_real, exp_belief))
    return np.asarray(z_vals_new)


def mean_and_var_preserving_states(z_vals, Π_real, Π_belief, err_tol, T=1000000):
    exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
    exp_belief = exp_val(z_vals=z_vals, P_z=Π_belief)
    z_vals_new = np.array(z_vals)
    diff_exp = exp_real - exp_belief
    weights_exp = MarkovChain(Π_belief).stationary_distributions[0]
    weights_exp[2] = weights_exp[1]
    weights_exp = weights_exp/sum(weights_exp)
    n = len(z_vals)
    
    var_real = np.sqrt(np.var(MarkovChain(Π_real, z_vals).simulate(T)))
    var_belief = np.sqrt(np.var(MarkovChain(Π_belief, z_vals).simulate(T)))
    weights_var = MarkovChain(Π_belief).stationary_distributions[0][0:3]
    weights_var[2] = weights_var[1]
    weights_var = weights_var/sum(weights_var)
    diff_var = var_belief - var_real
    
    while abs(diff_exp) > err_tol or abs(diff_var) > err_tol:
    
        while abs(diff_exp) > err_tol:
            for i, weight in enumerate(weights_exp):
                z_vals_new[i] += weight*diff_exp
        
            exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
            exp_belief = exp_val(z_vals=z_vals_new, P_z=Π_belief)
            diff_exp = exp_real - exp_belief
        
            var_real = np.sqrt(np.var(MarkovChain(Π_real, z_vals).simulate(T)))
            var_belief = np.sqrt(np.var(MarkovChain(Π_belief, z_vals_new).simulate(T)))
            diff_var = var_belief - var_real
    
        while abs(diff_var) > err_tol:
            for i, weight in enumerate(weights_var):
                if i == 0:
                    z_vals_new[i] -= weight*diff_var
                else:
                    z_vals_new[i] += weight*diff_var
                
            exp_real = exp_val(z_vals=z_vals, P_z=Π_real)
            exp_belief = exp_val(z_vals=z_vals_new, P_z=Π_belief)
            diff_exp = exp_real - exp_belief
        
            var_real = np.sqrt(np.var(MarkovChain(Π_real, z_vals).simulate(T)))
            var_belief = np.sqrt(np.var(MarkovChain(Π_belief, z_vals_new).simulate(T)))
            diff_var = var_belief - var_real
        
    print('means_err: {}'.format(diff_exp))
    print('variance_err: {}, real: {}, belief: {}'.format(diff_var, var_real, var_belief))
    print('r-shock state values: {}'.format(np.asarray(z_vals_new)))
    
    return np.asarray(z_vals_new)



In [63]:
P1, P3, epsilon = 0.6, 0.3, 0.005
z_vals = (1.5, 0.2, -0.5)

P_real, P_belief, z_vals = belief_decompose(trans_mat(P1,P3,epsilon), z_vals)

z_vals_new = mean_preserving_states(z_vals, 
                                    P_real, 
                                    P_belief, 
                                    1e-7)

# test whether the function works
exp_val(z_vals_new, P_belief), exp_val(z_vals, P_real)

(0.84315029357999483, 0.84315037929495773)

In [64]:
print('real matrix: \n \n{}'.format(P_real))
print('\n \n belief matrix: \n \n{}'.format(P_belief))
print('\n \n state space: \n \n{}'.format(z_vals))

real matrix: 
 
[[ 0.6    0.2    0.2    0.   ]
 [ 0.395  0.3    0.3    0.005]
 [ 0.395  0.3    0.3    0.005]
 [ 0.35   0.175  0.175  0.3  ]]

 
 belief matrix: 
 
[[ 0.6     0.2     0.2     0.    ]
 [ 0.1975  0.6     0.1975  0.005 ]
 [ 0.      0.      0.6     0.4   ]
 [ 0.35    0.35    0.      0.3   ]]

 
 state space: 
 
[ 1.5  0.2  0.2 -0.5]


When we are working with beliefs, we have to keep in mind that there are two kinds of 'realities' in this model.
<br\>
<br\>
One is the 'actual' reality where the 'real' values are realized by the 'real' transition matrix. The other one is the agent's 'belief-reality' where the agent makes decisions based on a belief-transition-matrix, he perceives the realizations differently than they are in the actual reality of the simulation of this model.
<br\>
<br\>
We are using a pessimistic belief-matrix. Consequently, in the agent's 'belief-reality', the realization of the interest rates will be much lower in average. Thus, the marginal utility of the assets will be much lower and then it's not so suprising that the agent is going to save less.
<br\>
<br\>
That's why I have written a code, which computes a mean-preserving-spread of the state values. When simulating the pessimistic case with a mean_preserving-spread, I should put the new state values only into the expactation of the agents as they are only the values of the states which are perceived by the agent and not the 'real' values.

In [65]:
# Then, I will write a class and corresponding functions, 
# which distinguish between the two different 
# kinds of transition matrices.

import numpy as np
from scipy.optimize import brentq
from quantecon import MarkovChain

class Pair:
    """
    This class, takes two markov processes, combines their state spaces
    and gives the corresponding transition matrix.
    """    
    
    def __init__(self,
                 a_vals = [0, 1], # state values of the first mc
                 b_vals = [1, 0], # state values of the second mc
                 P_a = [[0.9, 0.1], [0.1, 0.9]],
                 P_b = [[0.8, 0.2], [0.2, 0.8]]):
        
        self.a_vals = np.asarray(a_vals)
        self.b_vals = np.asarray(b_vals)
        self.P_a = np.asarray(P_a)
        self.P_b = np.asarray(P_b)
        self.n = len(a_vals) * len(b_vals)
        
        # Build the array with combined state values
        self.s_vals = make_statespace(self.a_vals, self.b_vals)
        
        # Combine both transition matrices
        self.Q = np.kron(self.P_b, self.P_a)
    

def make_statespace(a, b):
    """
    returns state space s_vals, when two statespaces of two independend markov 
    chains a, b are combined to s:=(a_state, b_state)
    
    Parameters
    ----------
    a,b : state spaces in form of numpy arrays containing the state values of
          the two markov chains a and b.
          
    Returns
    ---------
    state space vector : Returns a two-dimentional array 
                         [[a_state1, b_state1], [a_state2, b_state1], ...etc]
    """
    
    s_vals = []

    for j in range(len(b)):
        for i in range(len(a)):
            s_vals.append([a[i], b[j]])
    return np.array(s_vals)

def fixed_point(K, c_init, err_tol=1e-3, max_iter=300):
    i, c = 0, K(c_init)
    if np.linalg.norm((c-c_init))<err_tol:
        return c
    while max_iter>i and np.linalg.norm((c-c_init))>=err_tol:
        i=i+1
        c_init=c
        c=K(c_init)
    return np.asarray(c)

class canersHousehold:
    
    def __init__(self, 
                 r=0.03,
                 w=1,
                 β=0.96, 
                 Π_w=((0.6, 0.4), (0.05, 0.95)),
                 Π_r_real=((0.6, 0.4, 0), (0.35, 0.6, 0.05), (0.35, 0.35, 0.3)),
                 Π_r_belief=((0.6, 0.4, 0), (0.3, 0.6, 0.1), (0.35, 0.35, 0.3)),
                 z_w_vals=(0.5, 1.0),
                 z_r_vals=(1.5, 0.2, -0.5),
                 b=0, 
                 grid_max=16, 
                 grid_size=50,
                 du=lambda x: 1/x,
                 mean_preserved = False, 
                 mean_and_var_preserved = False):
        
        # simplify names, set up array and change the input
        # in a way so that you can adjust the coleman operator
        # and the simulation of assets, 
        # belief trans. matrix -> in coleman operator
        
        self.du, self.w, self.r = du, w, r
        self.grid_max, self.grid_size = grid_max, grid_size
        self.Π_w, self.z_w_vals = Π_w, z_w_vals
        self.β, self.b = β, b
        self.asset_grid = np.linspace(-b, grid_max, grid_size)
        self.mean_preserved = mean_preserved
        self.mean_and_var_preserved = mean_and_var_preserved
        
        self.Π_r_belief = np.asarray(Π_r_belief) 
        
        self.Π_r_real = np.asarray(Π_r_real)
        
        self.z_r_vals = np.asarray(z_r_vals)
        
        # perceived values
        
        if mean_preserved: 
            self.z_r_vals_mps = mean_preserving_states(self.z_r_vals,
                                                       self.Π_r_real,
                                                       self.Π_r_belief,
                                                       1e-7)
        elif mean_and_var_preserved:
            self.z_r_vals_mps = mean_and_var_preserving_states(self.z_r_vals,
                                                               self.Π_r_real,
                                                               self.Π_r_belief,
                                                               1e-4)
        
        # take the new transition matrices and combine them with
        # the transition matrix for the wage shock in order
        # to get Π_belief, Π_real and z_vals
        
        if mean_preserved or mean_and_var_preserved:
            self.z_belief = Pair(a_vals=self.z_r_vals_mps, # use perceived values here
                                 b_vals=z_w_vals,
                                 P_a=self.Π_r_belief,
                                 P_b=Π_w)
        else:
            
            self.z_belief = Pair(a_vals=self.z_r_vals,
                                 b_vals=z_w_vals,
                                 P_a=self.Π_r_belief,
                                 P_b=Π_w)
        
        self.z_real = Pair(a_vals=self.z_r_vals,
                           b_vals=z_w_vals,
                           P_a=self.Π_r_real,
                           P_b=Π_w)
        
        # you need two different state spaces, one for the simulation of the 
        # markov chain which needs the real values and the other one
        # for the operator which needs the belief values
        
        self.z_vals, self.z_belief_vals = self.z_real.s_vals, self.z_belief.s_vals
        self.Π_belief, self.Π_real = self.z_belief.Q, self.z_real.Q


def belief_operator(c, cp):
    
    # === simplify names, set up arrays === #
    r, Π_belief, β, du, b, w = cp.r, cp.Π_belief, cp.β, cp.du, cp.b, cp.w
    asset_grid, z_belief_vals = cp.asset_grid, cp.z_belief_vals
    z_size = len(z_belief_vals)
    vals = np.empty(z_size)
    
    def cf(a):
        for i in range(z_size):
            vals[i] = np.interp(a, asset_grid, c[:,i])
        return vals
    
    Kc = np.empty(c.shape)
    for i_a, a in enumerate(asset_grid):
        for i_z, z in enumerate(z_belief_vals):
            z_r, z_w = z[0], z[1]
            def h(t):
                expectation = np.dot(du(cf((1+r*z_r) * a + w * z_w - t)), Π_belief[i_z,:])
                return du(t) - max((1+r*z_r) * β * expectation, du((1+r*z_r) * a + w * z_w + b))
            Kc[i_a, i_z] = brentq(h, 1e-8, (1+r*z_r) * a + w * z_w + b)
    return Kc

def initialize(cp):
    # === Simplify names, set up arrays === #
    r, b, w = cp.r, cp.b, cp.w
    asset_grid, z_vals = cp.asset_grid, cp.z_belief_vals
    shape = len(asset_grid), len(z_vals)
    c = np.empty(shape)
    
    for i_a, a in enumerate(asset_grid):
        for i_z, z in enumerate(z_vals):
                z_r, z_w = z[0], z[1]
                c_max = (1+r*z_r) * a + w * z_w + b
                c[i_a, i_z] = c_max
    return c

def pessimistic_asset_series(cp,
                             T=250000,
                             max_iter=150):
    """
    Simulates a time series of length T for assets, given optimal savings
    behavior and pessimistic Beliefs. Parameter cp is an instance of canersPessimist.
    """
    
    Π_real, z_vals, r, w = cp.Π_real, cp.z_vals, cp.r, cp.w
    mc = MarkovChain(Π_real)
    c_init = initialize(cp)
    K = lambda c: belief_operator(c, cp)
    c = fixed_point(K=K, c_init=c_init, max_iter=max_iter)
    cf = lambda a, i_z: np.interp(a, cp.asset_grid, c[:, i_z])
    a = np.zeros(T+1)
    interest_rates = np.zeros(T)
    a[0]=1e-5
    z_seq = mc.simulate(T)
    for t in range(T):
        i_z = z_seq[t]
        a[t+1] = (1+r*z_vals[i_z][0]) * a[t] + w * z_vals[i_z][1] - cf(a[t], i_z)
        interest_rates[t] = r*z_vals[i_z][0]
    return a, interest_rates

In [66]:
cp = canersHousehold(mean_preserved=True)
cp.z_belief_vals

array([[ 1.65188765,  0.5       ],
       [ 0.2       ,  0.5       ],
       [-0.47520202,  0.5       ],
       [ 1.65188765,  1.        ],
       [ 0.2       ,  1.        ],
       [-0.47520202,  1.        ]])

In [67]:
# After that, I will simulate the asset choices given a interest rate, 
# compute the variance of the assets series and compare them.
P1, P3, epsilon, z_r_vals = 0.6, 0.3, 0.005, [1.5, 0.02, -0.5]
Π_r_real, Π_r_belief, z_r_vals = belief_decompose(trans_mat(P1, P3, epsilon),
                                              z_r_vals)
print('real matrix: \n \n{}'.format(Π_r_real))
print('\n \n belief matrix: \n \n{}'.format(Π_r_belief))
print('\n \n state space: \n \n{}'.format(z_r_vals))

real matrix: 
 
[[ 0.6    0.2    0.2    0.   ]
 [ 0.395  0.3    0.3    0.005]
 [ 0.395  0.3    0.3    0.005]
 [ 0.35   0.175  0.175  0.3  ]]

 
 belief matrix: 
 
[[ 0.6     0.2     0.2     0.    ]
 [ 0.1975  0.6     0.1975  0.005 ]
 [ 0.      0.      0.6     0.4   ]
 [ 0.35    0.35    0.      0.3   ]]

 
 state space: 
 
[ 1.5   0.02  0.02 -0.5 ]


In [68]:
import matplotlib.pyplot as plt
# create an instance of the household

# 2. case, pessimistic

Π_w, z_w_vals = (1), [1]
r=0.03
hh2 = canersHousehold(r=0.03,
                     b=0,
                     Π_r_real=Π_r_real, 
                     Π_r_belief=Π_r_belief,
                     Π_w=Π_w,
                     z_r_vals=z_r_vals, 
                     z_w_vals=z_w_vals)

#simulate the asset series
T=1000000
max_iter=300
a_p, r_p = pessimistic_asset_series(hh2,
                                    T=T,
                                    max_iter=max_iter)


In [69]:
# create an instance of the household

# 1. case, non-pessimistic

hh1 = canersHousehold(r=0.03,
                     b=0,
                     Π_r_real=Π_r_real, 
                     Π_r_belief=Π_r_real, # use the real matrix twice
                     Π_w=Π_w,
                     z_r_vals=z_r_vals, 
                     z_w_vals=z_w_vals)

#simulate the asset series
T=1000000
max_iter=300
a_np, r_np = pessimistic_asset_series(hh1,
                                      T=T,
                                      max_iter=max_iter)

In [70]:
# create an instance of the household

# 3. case, with pessimistic beliefs, mean-preserved-spread

hh3 = canersHousehold(r=0.03,
                     b=0,
                     Π_r_real=Π_r_real, 
                     Π_r_belief=Π_r_belief,
                     Π_w=Π_w,
                     z_r_vals=z_r_vals, 
                     z_w_vals=z_w_vals,
                     mean_preserved=True)

#simulate the asset series
T=1000000
max_iter=300
a_p_mp, r_p_mp = pessimistic_asset_series(hh3,
                                          T=T,
                                          max_iter=max_iter)

In [71]:
# create an instance of the household

# 4. case, with pessimistic beliefs, mean and var preserved

hh4 = canersHousehold(r=0.03,
                      b=0,
                      Π_r_real=Π_r_real, 
                      Π_r_belief=Π_r_belief,
                      Π_w=Π_w,
                      z_r_vals=z_r_vals, 
                      z_w_vals=z_w_vals,
                      mean_and_var_preserved = True)

#simulate the asset series
T=1000000
max_iter=300
a_p_mvp, r_p_mvp = pessimistic_asset_series(hh4,
                                          T=T,
                                          max_iter=max_iter)

means_err: 8.009267965114475e-05
variance_err: 9.50822539835805e-06, real: 0.7425326496465772, belief: 0.7425421578719755
r-shock state values: [ 1.86566111  0.48876377  0.48876377 -0.26016058]


In [72]:
hh.z_belief_vals

array([[ 2.82643065,  1.        ],
       [ 0.02      ,  1.        ],
       [ 0.02      ,  1.        ],
       [-0.3       ,  1.        ]])

In [73]:
std_ap, std_anp, std_apmp, std_apmvp = np.sqrt(np.var(np.log(a_p))), np.sqrt(np.var(np.log(a_np))), np.sqrt(np.var(np.log(a_p_mp))), np.sqrt(np.var(np.log(a_p_mvp)))
std_ap, std_anp, std_apmp, std_apmvp

mean_ap, mean_anp, mean_apmp, mean_apmvp = np.mean(np.log(a_p)), np.mean(np.log(a_np)), np.mean(np.log(a_p_mp)), np.mean(np.log(a_p_mvp)) 
mean_ap, mean_anp, mean_apmp, mean_apmvp

(-5.0018048542969167,
 -4.7891174047688176,
 -2.2451048534343858,
 -3.2005852805492805)

In [74]:
std_rp, std_rnp, std_rpmp, std_rpmvp = np.sqrt(np.var(r_p)), np.sqrt(np.var(r_np)), np.sqrt(np.var(r_p_mp)), np.sqrt(np.var(r_p_mvp))
std_rp, std_rnp, std_rpmp, std_rpmvp

mean_rp, mean_rnp, mean_rpmp, mean_rpmvp = np.mean(r_p), np.mean(r_np), np.mean(r_p_mp), np.mean(r_p_mvp) 
mean_rp, mean_rnp, mean_rpmp, mean_rpmvp

(0.022603294799999986,
 0.022604973599999998,
 0.022667592000000004,
 0.022593658799999992)

In [75]:
import pandas as pd

assets = [{'log-assets': 'non-pessisimistic assets', 'mean': mean_anp, 'std': std_anp},
         {'log-assets': 'pessisimistic assets',  'mean': mean_ap, 'std': std_ap},
         {'log-assets': 'pessisimistic assets, mean-preserved',  'mean': mean_apmp,  'std': std_apmp},
         {'log-assets': 'pessisimistic assets, mean-var-preserved',  'mean': mean_apmvp,  'std': std_apmvp}]
dfa = pd.DataFrame(assets)
dfa0 = dfa.set_index('log-assets')
dfa0

mean       std
log-assets                                                  
non-pessisimistic assets                 -4.789117  0.799966
pessisimistic assets                     -5.001805  0.917110
pessisimistic assets, mean-preserved     -2.245105  0.810324
pessisimistic assets, mean-var-preserved -3.200585  0.736879

In [76]:
interest_rates = [{'interest-rates': 'non-pessisimistic case', 'mean': mean_rnp, 'std': std_rnp},
         {'interest-rates': 'pessisimistic case',  'mean': mean_rp, 'std': std_rp},
         {'interest-rates': 'pessisimistic case, mean-preserved',  'mean': mean_rpmp,  'std': std_rpmp},
         {'interest-rates': 'pessisimistic case, mean-var-preserved',  'mean': mean_rpmvp,  'std': std_rpmvp}]
dfi = pd.DataFrame(interest_rates)
dfi0 = dfi.set_index('interest-rates')
dfi0

mean       std
interest-rates                                            
non-pessisimistic case                  0.022605  0.022272
pessisimistic case                      0.022603  0.022275
pessisimistic case, mean-preserved      0.022668  0.022278
pessisimistic case, mean-var-preserved  0.022594  0.022275

In [77]:
from quantecon import MarkovChain
z_r_vals_mps = hh3.z_r_vals_mps
z_r_vals_mvp = hh4.z_r_vals_mps

# Let's simulate the interest rates how they are perceived by the agents in each case
T=1000000
r=0.03
# 1. case, non-pessimistic
perceived_mc_np = MarkovChain(Π_r_real, state_values=r*z_r_vals)
pr_np = perceived_mc_np.simulate(T)

# 2. case, pessimmistic
perceived_mc_p = MarkovChain(Π_r_belief, state_values=r*z_r_vals)
pr_p = perceived_mc_p.simulate(T)


# 3. case, pessimistic mean-presreved 
perceived_mc_pmp = MarkovChain(Π_r_belief, state_values=r*z_r_vals_mps)
pr_p_mp = perceived_mc_pmp.simulate(T)

# 3. case, pessimistic mean-and-var-presreved 
perceived_mc_pmvp = MarkovChain(Π_r_belief, state_values=r*z_r_vals_mvp)
pr_p_mvp = perceived_mc_pmvp.simulate(T)

In [78]:
pstd_rp, pstd_rnp, pstd_rpmp, pstd_rpmvp = np.sqrt(np.var(pr_p)), np.sqrt(np.var(pr_np)), np.sqrt(np.var(pr_p_mp)), np.sqrt(np.var(pr_p_mvp))
pstd_rp, pstd_rnp, pstd_rpmp, pstd_rpmvp

(0.02218289795334253,
 0.022273730617619513,
 0.038863347534608468,
 0.022269455597158382)

In [79]:
pmean_rp, pmean_rnp, pmean_rpmp, pmean_rpmvp = np.mean(pr_p), np.mean(pr_np), np.mean(pr_p_mp), np.mean(pr_p_mvp)
pmean_rp, pmean_rnp, pmean_rpmp, pmean_rpmvp

(0.010489642799999995,
 0.02267123519999999,
 0.022525871333098201,
 0.022630919789472601)

In [80]:
perceived_interest_rates = [{'perceived interest-rates': 'non-pessisimistic case', 'mean': pmean_rnp, 'std': pstd_rnp},
         {'perceived interest-rates': 'pessisimistic case',  'mean': pmean_rp, 'std': pstd_rp},
         {'perceived interest-rates': 'pessisimistic case, mean-preserved',  'mean': pmean_rpmp,  'std': pstd_rpmp},
         {'perceived interest-rates': 'pessisimistic case, mean-var-preserved',  'mean': pmean_rpmvp,  'std': pstd_rpmvp}]
dfpi = pd.DataFrame(perceived_interest_rates)
dfpi0 = dfpi.set_index('perceived interest-rates')
dfpi0

mean       std
perceived interest-rates                                  
non-pessisimistic case                  0.022671  0.022274
pessisimistic case                      0.010490  0.022183
pessisimistic case, mean-preserved      0.022526  0.038863
pessisimistic case, mean-var-preserved  0.022631  0.022269

In [81]:
dfa0.to_latex('variances.tex')
dfi0.to_latex('variances2.tex')
dfpi0.to_latex('variances3.tex')

In [ ]:
pmean_rpmp